### Health check
GET {{ baseUrl }}/healthz
Accept: application/json

###

### Readiness check
GET {{ baseUrl }}/readyz
Accept: application/json

###

### Queue quote update
POST {{ baseUrl }}/quotes/updates
Content-Type: application/json
X-Idempotency-Key: demo-27

{
  "pair": "EUR/USD"
}

###

# Get quote by id
GET {{ baseUrl }}/quotes/updates/9d5fa612-01a7-465f-9fb6-a496e0b21d5a
Accept: application/json

###

# Get last quote
GET {{ baseUrl }}/quotes/last?pair=EUR/USD
Accept: application/json


