### Health check
GET {{ baseUrl }}/healthz
Accept: application/json

### Readiness check
GET {{ baseUrl }}/readyz
Accept: application/json

###

### Queue quote update
POST {{ baseUrl }}/quotes/updates
Content-Type: application/json
X-Idempotency-Key: demo-16

{
  "pair": "MXN/EUR"
}

###

# Get quote by id
GET {{ baseUrl }}/quotes/updates/6eadb470-30f6-4f13-8120-4029587ee0c1
Accept: application/json

###

# Get last quote
GET {{ baseUrl }}/quotes/last?pair=EUR/USD
Accept: application/json


