### Health check
GET http://localhost:8080/healthz
Accept: application/json

###

### Readiness check
GET http://localhost:8080/readyz
Accept: application/json

###

### Queue quote update
POST http://localhost:8080/quotes/updates
Content-Type: application/json
X-Idempotency-Key: demo-27

{
  "pair": "EUR/USD"
}

###

# Get quote by id
GET http://localhost:8080/quotes/updates/a0ae1ab8-aa07-4409-87e4-06d3f0129e3a
Accept: application/json

###

# Get last quote
GET http://localhost:8080/quotes/last?pair=EUR/USD
Accept: application/json


