// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"fxrates-service/internal/application"
	"fxrates-service/internal/infrastructure/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

// API injector: builds *httpserver.Server + Cleanup
func InitAPI(ctx context.Context) (*httpserver.Server, func(), error) {
	logger := ProvideLogger()
	config := ProvideConfig()
	db, cleanup, err := ProvideDB(ctx, logger, config)
	if err != nil {
		return nil, nil, err
	}
	repos := ProvideRepos(db)
	rateProvider, err := ProvideRateProvider(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup2, err := ProvideRedisClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	services := ProvideIdempotency(client, config)
	unitOfWork := ProvideUoW(db)
	fxRatesService := ProvideFXRatesService(repos, rateProvider, services, unitOfWork)
	server := httpserver.NewServer(fxRatesService)
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}

// DB Worker injector: builds application.Worker + Cleanup
func InitDBWorker(ctx context.Context) (application.Worker, func(), error) {
	logger := ProvideLogger()
	config := ProvideConfig()
	db, cleanup, err := ProvideDB(ctx, logger, config)
	if err != nil {
		return nil, nil, err
	}
	repos := ProvideRepos(db)
	rateProvider, err := ProvideRateProvider(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup2, err := ProvideRedisClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	services := ProvideIdempotency(client, config)
	unitOfWork := ProvideUoW(db)
	fxRatesService := ProvideFXRatesService(repos, rateProvider, services, unitOfWork)
	worker := ProvideWorker(fxRatesService, rateProvider, logger, config)
	return worker, func() {
		cleanup2()
		cleanup()
	}, nil
}

// gRPC Runner injector: builds gRPC server runner + Cleanup
func InitGRPCRunner(ctx context.Context) (func(context.Context) error, func(), error) {
	config := ProvideConfig()
	rateProvider, err := ProvideRateProvider(config)
	if err != nil {
		return nil, nil, err
	}
	logger := ProvideLogger()
	v := ProvideGRPCRateServerRunner(config, rateProvider, logger)
	return v, func() {
	}, nil
}

// wire.go:

var infraSet = wire.NewSet(
	ProvideLogger,
	ProvideConfig,
	ProvideDB,
	ProvideRepos,
	ProvideUoW,
	ProvideRedisClient,
	ProvideIdempotency,
	ProvideRateProvider,
	ProvideFXRatesService,
	ProvideGRPCRateClient,
)
