// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"fxrates-service/internal/application"
	"fxrates-service/internal/infrastructure/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

// API injector: builds *httpserver.Server + Cleanup
func InitAPI(ctx context.Context) (*httpserver.Server, func(), error) {
	logger := ProvideLogger()
	config := ProvideConfig()
	db, cleanup, err := ProvideDB(ctx, logger, config)
	if err != nil {
		return nil, nil, err
	}
	repos := ProvideRepos(db)
	rateProvider, err := ProvideRateProvider(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup2, err := ProvideRedisClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	services := ProvideIdempotency(client, config)
	fxRatesService := ProvideFXRatesService(repos, rateProvider, services)
	grpcClient, cleanup3, err := ProvideGRPCRateClient(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server := httpserver.NewServer(fxRatesService)
	// Set DB readiness check for /readyz
	server.SetReadyCheck(func(ctx context.Context) error {
		return db.Ping(ctx)
	})
	// Attach optional gRPC background client when in grpc mode
	server.AttachGRPCBackground(repos.QuoteRepo, repos.JobRepo, grpcClient, config)
	return server, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// Worker injector: builds application.Worker or gRPC server runner + Cleanup
func InitWorker(ctx context.Context) (application.Worker, func(context.Context) error, func(), error) {
	logger := ProvideLogger()
	config := ProvideConfig()
	// gRPC server runner path (no DB on worker)
	rateProvider, err := ProvideRateProvider(config)
	if err != nil {
		return nil, nil, nil, err
	}
	// gRPC server runner path
	if runner, ok := ProvideGRPCRateServerRunner(config, rateProvider, logger); ok {
		return nil, runner, func() {
		}, nil
	}
	// DB worker path
	db, cleanup, err := ProvideDB(ctx, logger, config)
	if err != nil {
		return nil, nil, nil, err
	}
	repos := ProvideRepos(db)
	worker := ProvideWorker(repos, rateProvider, logger, config)
	return worker, nil, func() {
		cleanup()
	}, nil
}

// wire.go:

var infraSet = wire.NewSet(
	ProvideLogger,
	ProvideConfig,
	ProvideDB,
	ProvideRepos,
	ProvideRedisClient,
	ProvideIdempotency,
	ProvideRateProvider,
	ProvideFXRatesService,
	ProvideGRPCRateClient,
)
