// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"fxrates-service/internal/application"
	"fxrates-service/internal/infrastructure/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

// API injector: builds *httpserver.Server + Cleanup
func InitAPI(ctx context.Context) (*httpserver.Server, func(), error) {
	logger := ProvideLogger()
	db, cleanup, err := ProvideDB(ctx, logger)
	if err != nil {
		return nil, nil, err
	}
	repos := ProvideRepos(db)
	rateProvider, err := ProvideRateProvider()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup2, err := ProvideRedisClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	services := ProvideIdempotency(client)
	fxRatesService := ProvideFXRatesService(repos, rateProvider, services)
	server := httpserver.NewServer(fxRatesService)
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}

// Worker injector: builds application.Worker + Cleanup
func InitWorker(ctx context.Context) (application.Worker, func(), error) {
	logger := ProvideLogger()
	db, cleanup, err := ProvideDB(ctx, logger)
	if err != nil {
		return nil, nil, err
	}
	repos := ProvideRepos(db)
	rateProvider, err := ProvideRateProvider()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	worker := ProvideWorker(repos, rateProvider, logger)
	return worker, func() {
		cleanup()
	}, nil
}

// wire.go:

var infraSet = wire.NewSet(
	ProvideLogger,
	ProvideDB,
	ProvideRepos,
	ProvideRedisClient,
	ProvideIdempotency,
	ProvideRateProvider,
	ProvideFXRatesService,
)
