# ops/compose.dev.yml
- name: Bring up fxrates stack with Compose v2
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - "{{ playbook_dir }}/secrets/dev.yml"

  tasks:
    - name: Up/Restart stack
      community.docker.docker_compose_v2:
        project_src: "{{ playbook_dir }}/docker"
        files: [docker-compose.yml]
        state: present
        build: always
        pull: missing
        remove_orphans: true
        recreate: auto
      environment:
        PROVIDER: "exchangeratesapi"
        EXCHANGE_API_BASE: "{{ env.EXCHANGE_API_BASE }}"
        EXCHANGE_API_KEY: "{{ env.EXCHANGE_API_KEY }}"
